### PR TITLE
Integration plugin docs repeteadly genereted issue fix.

### LINKED ISSUE #79: Plugin doc generation: preserve content in logstash-docs if no version bump (integrations)
Version 2.0 of issue #45 and PR #72 to add same [wonderful, time-saving!] logic for integration component plugins.

"Destination Wins"

A plugin version bump triggers the docgen scripts to pick up doc changes for inclusion in a PR. If there isn't a version bump, the script should not pick up doc content. When it does, I often have to back out the changes to pass CI and avoid breaking the docs build.  

The fix implemented in #72 works for stand-alone plugins, but does not appear to be working for plugins that are part of an integration (codec-cloudtrail and codec-cloudwatch that belong to the AWS integration, for example).  While we're working through some docgen kinks, I made manual updates to those two codecs. The next docgen stomped my changes: 
* https://github.com/elastic/logstash-docs/pull/1410
* https://github.com/elastic/logstash-docs/pull/1411

In the docs, these codecs are "children" of the aws integration rather than stand-alone plugins. That's why I think the fix for stand-alone plugins doesn't cover them.

### LINKED ISSUE #80: Docs for some integration plugin components aren't getting updated
#### Specifics
* Logstash Reference (LSR) 
* AWS integration 7.0.0
   * codec-cloudfront
   * codec-cloudtrail

#### Details
When we create a new integration plugin and "adopt" formerly stand-alone plugins, the integration and child plugins are all expected to update in tandem to the next major version (AWS 7.0.0). For the AWS integration, the version number/release date on the two codec plugins--cloudfront and cloudtrail--are not getting updated.  Here's an example of an early PR where this problem presented itself: https://github.com/elastic/logstash-docs/pull/1400.

#### Short-term remediation
As a short-term work-aound, I manually bumped the release date/version in the output files in `logstash-docs`.

When we run the doc generation job for affected branches, the resulting PR contains files with the old version and release date. Obviously, we don't want to introduce regressions, so I have to make manual fixes on the PR. Here's the fix we need to address this secondary problem: https://github.com/elastic/docs-tools/issues/79.

#### Other notes
* This issue applies only to Logstash Reference (LSR) plugin generation. The Versioned Plugin Reference (VPR) plugin generation uses different tooling and is not impacted. 
* This issue could possibly be related to settings (lockfiles, skiplists, etc.) rather than a problem with docs tooling.   If that's the case, we need to fix that elsewhere and/or update "Adding integration docs" internal documentation as another checklist item. 
* As with most docs-tooling issues, testing might be tricky because we'll need to bump version and publish to fully test.

### PR DESCRIPTION
**Pull request by mashhurs**
### Issue description
When generating Plugin Reference Docs, embedded integration plugin meta changes are not correctly picked up. #79 and #80 issues are relative.

#80 happens when logstash machine generates the doc first and re-tries to generate with `skip-existing` option. So unnecessary contents will appear for the second try.

Closes #79 
Closes #80 

### Acceptance criteria
Embedded plugin should follow the integration plugin and use its meta data in the docs.

### What does this PR introduce?
Logic generates the `plugins_version_docs.json` which contains the list of repositories with plugin details (default plugin and version, etc...). We iterate thought the repositories and generate the doc one-by-one for each plugin as well as plugin's dependencies (embedded and aliased plugins). There is a discrepancy which same job is repeated on same plugin with different information. Eg. the repository entry `integration-aws` doc generation includes `codec-cloudfront` embedded plugin and `integration-aws` info (version, change log URL, etc..) used for `codec-cloudfront` docs in same loop. However, when repository entry reaches `codec-cloudfront`, it also repeats doc generation with cloudfront's info (version, change log URL) which is the issue.
This PR introduces the a logic to avoid the repetition which was the bottleneck. 
Note that, for the short term we are making a process single since there will be a race condition on `processed_plugins` DS.

### Test
- Reproduces both cases on my local. Run to check with following command:
`bundle exec ruby plugindocs.rb --parallelism 1  --skip-existing --output-path ../logstash-docs ../logstash/plugins_version_docs.json`

### CODE REVIEW

**Review by yaauie — COMMENTED** [review]
When there is a collision between an integrat_ed_ plugin and a stand-alone plugin, I _believe_ we want the integration plugin to win (partially because we assume that we will only combine stand-alones _into_ integrations and not break-apart integrat_ed_ plugins into stand-alones).

As-implemented, this depends on `--parallelism 1` and without it is subject to surprising behaviour in a race condition, in which neither is guaranteed to "win".

 - integrated marks before stand-alone checks: only integrated written ✅ 
 - integrated marks after stand-alone checks: last write wins, depends on encounter order ❌   

***

Off the top of my head, I don't have a good idea of how to always favor integrated plugins over stand-alone plugins without (1) removing the parallelism and (2) pre-sorting to ensure that we encounter all integrat_ion_ plugins (and their integrat_ed_ plugins) before any stand-alone plugins.

~~~ ruby
repositiories.sort_by { |name,_|  name.include?('-integration-') ? 0 : 1 }.each do |repository_name, details|
~~~

File: plugindocs.rb [hunk 1]
```diff
@@ -27,7 +28,13 @@ def execute
 
     alias_definitions = Util::AliasDefinitionsLoader.get_alias_definitions
 
+    # cache the processed plugins to prevent re-process with wrapped and alias plugins
+    processed_plugins = Set.new
+
```
Comment (karenzone) [inline plugindocs.rb:33]: Interesting! Thank you.

**Comment by karenzone** [comment]
Update: I used current docgen tooling to generate a baseline set of plugins for 7.17.  We didn't pick up any changes (as expected).  The AWS integration isn't in 7.17, and therefore the regressions aren't present either.  Again, as expected.

**Comment by mashhurs** [comment]
Thanks @karenzone to validate the changes with testings. Highly appreciate!

File: plugindocs.rb [hunk 2]
```diff
@@ -27,7 +35,13 @@ def execute
 
     alias_definitions = Util::AliasDefinitionsLoader.get_alias_definitions
 
-    repositories.peach(parallelism) do |repository_name, details|
+    # we need to sort to be sure we generate docs first for embedded plugins of integration plugins
+    # and skip the process for stand-alone plugin if already processed
+    sorted_repositories = repositories.sort_by { |name,_|  name.include?('-integration-') ? 0 : 1 }
+    sorted_repositories.peach(parallelism) do |repository_name, details|
```
Comment (yaauie) [inline plugindocs.rb:41]:
```suggestion
    if parallelism > 1
      $stderr.puts("WARN: --parallelism is temporarily constrained to 1\n")
    end
    sorted_repositories.each do |repository_name, details|
```

**Review by yaauie — COMMENTED** [review]
I haven't been able to get back into the head-space of concurrency guarantees, so even though you have work here to safeguard concurrent access to the which-one-wins detection, I'm not confident in actually _reviewing it_.

Instead of holding this useful fix up in a forever-queue, I believe we can temporarily constrain the parallelism to 1 for this execution mode (read: _not VPR_), and go with your as-proposed changes for ensuring that we handle integration plugins before stand-alones.

File: plugindocs.rb (hunk 2 above)
Comment (karenzone) [reply plugindocs.rb:41]: >Instead of holding this useful fix up in a forever-queue, I believe we can temporarily constrain the parallelism to 1 for this execution mode (read: not VPR), and go with your as-proposed changes for ensuring that we handle integration plugins before stand-alones.

^^ Yes, please. 😄 
I will need to make manual fixes to every PR for every branch until this gets merged.  Recent examples:
* https://github.com/elastic/logstash-docs/pull/1426
* https://github.com/elastic/logstash-docs/pull/1427

Comment (mashhurs) [reply plugindocs.rb]: Agreed! Placed some comments and applied the change.

File: plugindocs.rb [hunk 3]
```diff
@@ -1,24 +1,32 @@
...
-require "pmap" # Enumerable#peach
 
 require_relative 'lib/logstash-docket'
 
 class PluginDocs < Clamp::Command
   option "--output-path", "OUTPUT", "Path to the top-level of the logstash-docs path to write the output.", required: true
   option "--main", :flag, "Fetch the plugin's docs from main instead of the version found in PLUGINS_JSON", :default => false
   option "--settings", "SETTINGS_YAML", "Path to the settings file.", :default => File.join(File.dirname(__FILE__), "settings.yml"), :attribute_name => :settings_path
-  option("--parallelism", "NUMBER", "for performance", default: 4) { |v| Integer(v) }
+  option("--parallelism", "NUMBER", "for performance", default: 1) { |v| Integer(v) }
```
Comment (yaauie) [inline plugindocs.rb:17]: Since we constrain where needed in the non-versioned doc gen, we don't need to change the default. Having a default of 4 makes the versioned-plugin-reference _much_ faster.

```suggestion
  option("--parallelism", "NUMBER", "for performance", default: 4) { |v| Integer(v) }
```

**Review by yaauie — COMMENTED** [review]
One nit about keeping parallelism by default for the versioned plugin reference, otherwise LGTM.

**Review by yaauie — APPROVED** [review]
